### ISSUE TITLE
Crash on non MCG servers or servers with different tab list behaviour

### ISSUE THREAD

**Issue by forkiesassds** [SpiralP/classicube-chatsounds-plugin#5]
![image](https://user-images.githubusercontent.com/54495659/166261435-e4d6de77-902c-4b98-a60f-9f904bb15e7c.png)

**Comment by forkiesassds** [comment]
upstream issue, not issue with chatsounds

**Comment by SpiralP** [comment]
https://github.com/SpiralP/rust-classicube-helpers/issues/1
